name: 'Setup Dependencies'
description: 'Checkout code, setup npmrc, and setup node with yarn'

inputs:
  persist_credentials:
    description: 'Whether to persist credentials for checkout'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        persist-credentials: ${{ inputs.persist_credentials }}

    - name: Set up npmrc
      uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea
      with:
        script: const { installSdkPreview } = await import("${{github.workspace}}/src/scripts/install-sdk-preview.mjs");
          installSdkPreview(context, core);
      env:
        PACKAGE_READ_AUTH_TOKEN: ${{ secrets.PACKAGE_READ_AUTH_TOKEN }}

    - name: Set up node
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version: lts/*
        cache: yarn

    - name: Install dependencies
      run: yarn install --frozen-lockfile
      shell: bash
