name: Add Token
description: Creates a request to add a token to CoW Swap's default token list
title: '[AddToken] `SYMBOL` on `NETWORK`'
labels: [addToken]

body:
  - type: markdown
    attributes:
      value: |
        # Request to ADD token
        Thank you for contributing to CoW Swap's default token list.

        Please fill in all the required fields in the form.
        We will process and evaluate your request as soon as possible.

        Also, don't forget to update the issue title adding your token's `SYMBOL` and `NETWORK`.

        ## Disclaimer
        CoW DAO reserves the right, at its sole discretion, to accept or reject the listing of any token.
        This decision may be based on a variety of factors, including but not limited to, the token's technical soundness,
        regulatory compliance, project reputation, and overall alignment with CoW DAO's values and mission.

        The listing of a token on CoW Swap does not constitute an endorsement of the token, its associated project, or its team.
        Listing a token simply indicates that it meets the technical requirements for inclusion on the platform.

  - type: dropdown
    id: network
    attributes:
      label: Network
      description: The network this token is deployed to. If more than one, open another request.
      multiple: false
      options:
        - MAINNET
        - GNOSIS_CHAIN
        - ARBITRUM_ONE
    validations:
      required: true
  - type: input
    id: symbol
    attributes:
      label: Token Symbol
      description: The token symbol cannot contain spaces
      placeholder: SYMBOL
    validations:
      required: true
  - type: input
    id: name
    attributes:
      label: Token Name
      placeholder: My Token
    validations:
      required: true
  - type: input
    id: decimals
    attributes:
      label: Decimals
      value: '18'
    validations:
      required: true
  - type: input
    id: address
    attributes:
      label: Address
      placeholder: 0x...
    validations:
      required: true
  - type: input
    id: imageUrl
    attributes:
      label: Image URL
      description: Ideally a 256x256 PNG file. But we'll take care of optimizing it later.
      placeholder: https://gateway.pinata.cloud/ipfs/Qme9B6jRpGtZsRFcPjHvA5T4ugFuL4c3SzWfxyMPa59AMo
    validations:
      required: true
  - type: textarea
    id: reason
    attributes:
      label: Reason
      description: Why should we add this token? How do we know it's not a scam? Does it have enough liquidity on selected chain?
    validations:
      required: true
