name: Remove Token
description: Creates a request to remove a token from CoW Swap's default token list
title: "[RemoveToken] `SYMBOL` on `NETWORK`"
labels: [removeToken]

body:
  - type: markdown
    attributes:
      value: |
        # Request to REMOVE token
        Thank you for contributing to CoW Swap's default token list.
        
        Please fill in all the required fields in the form. 
        We will process and evaluate your request as soon as possible.
        
        Also, don't forget to update the issue title adding your token's `SYMBOL` and `NETWORK` (MAINNET or GNOSIS_CHAIN) 

  - type: dropdown
    id: network
    attributes:
      label: Network
      description: The network this token is deployed to. If more than one, open another request.
      multiple: false
      options:
        - MAINNET
        - GNOSIS_CHAIN
    validations:
      required: true
  - type: input
    id: address
    attributes:
      label: Address
      placeholder: 0x...
    validations:
      required: true
  - type: textarea
    id: reason
    attributes:
      label: Reason
      description: Why should we remove this token?
    validations:
      required: true
