name: Add Token
description: Creates a request to add a token to CoW Swap's default token list
title: "[AddToken] `SYMBOL` on `NETWORK`"
labels: [addToken]

body:
  - type: markdown
    attributes:
      value: |
        # Request to ADD token
        Thank you for contributing to CoW Swap's default token list.
        
        Please fill in all the required fields in the form. 
        We will process and evaluate your request as soon as possible.
        
        Also, don't forget to update the issue title adding your token's `SYMBOL` and `NETWORK` (MAINNET or GNOSIS_CHAIN) 

  - type: dropdown
    id: network
    attributes:
      label: Network
      description: The network this token is deployed to. If more than one, open another request.
      multiple: false
      options:
        - MAINNET
        - GNOSIS_CHAIN
    validations:
      required: true
  - type: input
    id: symbol
    attributes:
      label: Token Symbol
      placeholder: SYMBOL
    validations:
      required: true
  - type: input
    id: name
    attributes:
      label: Token Name
      placeholder: My Token
    validations:
      required: true
  - type: input
    id: decimals
    attributes:
      label: Decimals
      value: '18'
    validations:
      required: true
  - type: input
    id: address
    attributes:
      label: Address
      placeholder: 0x...
    validations:
      required: true
  - type: input
    id: imageUrl
    attributes:
      label: Image URL
      description: Ideally a 256x256 PNG file. But we'll take care of optimizing it later.
      placeholder: https://gateway.pinata.cloud/ipfs/Qme9B6jRpGtZsRFcPjHvA5T4ugFuL4c3SzWfxyMPa59AMo
    validations:
      required: true
  - type: textarea
    id: reason
    attributes:
      label: Why should we add this token? How do we know it's not a scam? Does it have enough liquidity on selected chain?
    validations:
      required: true
