name: CI

on:
  # Build on PR creation/updates, also when pushing to main/develop, or create a release
  pull_request:
    types: [opened, synchronize]
  push:
    branches: [main, develop]
    tags: [v*]

jobs:
  validate:
    name: Validate list schema
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Set up Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: lts/*
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run validation
        run: yarn validate

      - name: Run tests
        run: yarn test
