name: ProcessRequest

on:
  issues:
    types: [opened]

jobs:
  printContext:
    runs-on: ubuntu-latest
    steps:
      - env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: |
          echo $EVENT_CONTEXT

  callOptimizeImageWorkflow:
#    name: Call Optimize Image Workflow
    uses: ./.github/workflows/optimizeImage.yml
    secrets: inherit
    with:
      imageUrl: https://cdn.discordapp.com/attachments/913387055596326952/1072648112692285471/GODS.png
  addImage:
    runs-on: ubuntu-latest
    needs: callOptimizeImageWorkflow
    if: ${{ contains(github.event.labels.*.name, 'addImage') }}
    steps:
      - run: echo ${{ needs.process_image.outputs.imageBin }}